string = input("Enter the string\n")

print(string.upper())
print(string.lower())
print(string.rstrip("!"))
print(string.replace("Priyanka","Pooja"))
print(string.split(" "))
print(string.capitalize())
print(string.center(50))
print(string.count("a"))
print(string.endswith("a"))
print(string.find("o"))
print(string.index("a"))
print(string.isalum())
print(string.isalpha())
print(string.islower())
print(string.isupper())
print(string.isprintable())
print(string.isspace())
print(string.istitle())
print(string.startswith("P"))
print(string.swapcase())
print(string.title())